### ISSUE TITLE
실험일정

### ISSUE THREAD

**Issue by CheolJ** [AMLdatascience/crack-cycle-analyzer#1]
## 실험 일정 및 데이터 정리

10/7일 전까지 실험을 진행해보고, 나온 데이터들 같이 한번 정리하면 좋을 것 같습니다.
어떻게 생각하는지 의견주세요!

**Comment by CheolJ** [comment]
### 교수님과 미팅 일정

교수님이랑 데이터 정리한 자료들 기반으로해서 언제 얘기하는게 좋을지도 얘기해주면 좋을 것 같습니다!

**Comment by HongSungUk** [comment]
- 센서 3개 만들어서 결과가 뽑히는 대로 바로 교수님과 미팅!
